const ratings = {
    "...I Care Because You Do": 3.3,
    "'77 LIVE (2022 Remastered)": 3.5,
    "2": 4.7,
    "A Moon Shaped Pool": 3.9,
    "Abbey Road (Remastered)": 4.9,
    "After the Gold Rush (2009 Remaster)": 4.3,
    "Ágætis byrjun": 3.2,
    "Algernon Cadwallader": 3.9,
    "All Things Must Pass (Remastered)": 4.3,
    "Amber": 3.8,
    "American Football": 5,
    "Amnesiac": 3.7,
    "An Awesome Wave": 3.6,
    "Analphabetapolothology": 4.8,
    "Another Green World (2004 Remaster)": 3.7,
    "Ants From Up There (Deluxe)": 4.9,
    "Beach Music": 4.8,
    "Beat": 3.5,
    "Blonde On Blonde": 4,
    "Blood On The Tracks": 4.2,
    "Born Under A Bad Sign (Mono)": 3.5,
    "Bringing It All Back Home": 3.6,
    "Bryter Layter": 3.5,
    "Chet Baker Sings": 4.4,
    "Crooked Rain, Crooked Rain": 3.6,
    "Deathconsciousness": 4.5,
    "Demos": 4.2,
    "Disintegration (2010 Remaster)": 4.6,
    "Doolittle": 4.7,
    "Dragon New Warm Mountain I Believe In You": 4.0,
    "DSU": 4.8,
    "Duster": 3.0,
    "Ege Bamyasi (Remastered Version)": 3.7,
    "Either/Or": 5,
    "Elliott Smith": 4.5,
    "Ethiopiques, Vol. 4: Ethio Jazz 1969-1974": 4.3,
    "Everybody Knows This Is Nowhere": 3.6,
    "Everything Seems Better Now": 3.7,
    "Exuma, The Obeah Man": 3.2,
    "Feels": 4.2,
    "Filth": 2,
    "For Cameron": 3.5,
    "For the first time": 3.3,
    "Forever Changes (2015 Remaster)": 4.6,
    "Funeral": 3.7,
    "Fuzz": 3.2,
    "G_d's Pee AT STATE'S END!": 3.8,
    "God Save The Animals": 3.8,
    "good kid, m.A.A.d city (Deluxe)": 3.9,
    "Government Plates": 3.6,
    "Gris Gris": 3.2,
    "Harvest (2009 Remaster)": 3.7,
    "Hatful of Hollow": 4.3,
    "Help! (Remastered)": 3.7,
    "Heroes (1999 Remaster)": 3.9,
    "House of Sugar": 4.3,
    "Hunky Dory": 4.5,
    "If You’re Feeling Sinister": 4.1,
    "If You're Into It I'm Out of It": 3.1,
    "In Rainbows": 4.9,
    "In the Aeroplane Over the Sea": 4.9,
    "InnerSpeaker": 3.9,
    "Inside Jokes": 4.8,
    "Is This It": 4.9,
    "Just Got Back from the Discomfort We're Alright": 5,
    "Kid A": 4.9,
    "King Tubbys Meets Rockers Uptown": 3.6,
    "KXLU Session": 3.8,
    "Laughing Stock": 5,
    "Leak 04-13 (Bait Ones)": 4.7,
    "Let It Be (Remastered)": 4.3,
    "Lift Your Skinny Fists Like Antennas to Heaven": 4.4,
    "Loaded (2015 Remaster)": 4.6,
    "Lonerism": 3.9,
    "Loveless": 5,
    "Low (1999 Remaster)": 4.5,
    "m b v": 3.4,
    "Madvillainy": 4,
    "Magical Mystery Tour (Remastered)": 4.7,
    "Man Alive!": 3.8,
    "Marquee Moon": 3.8,
    "Masked Dancers: Concern in So Many Things You Forget Where You Are": 4.2,
    "Meat Is Murder": 3.6,
    "Melted": 2.9,
    "Merriweather Post Pavilion": 4,
    "Mount Eerie": 3.9,
    "MTV Unplugged In New York": 4.1,
    "Music Has The Right To Children": 3.6,
    "Nashville Skyline": 4.3,
    "OK Computer OKNOTOK 1997 2017": 4.7,
    "On Avery Island": 3.7,
    "On the Beach": 4.8,
    "Pet Sounds": 3.9,
    "Pink Moon": 5,
    "Plastic Ono Band": 4.5,
    "please be nice": 3.2,
    "Pornography": 3.9,
    "Race": 5,
    "Remain in Light": 4.7,
    "RePorpoised Phantasies": 3.4,
    "Reverse Shark Attack": 4.8,
    "Revolver (Remastered)": 4.9,
    "Richard D. James Album": 3.4,
    "Rock and Roll Night Club": 5,
    "Rocket": 4,
    "Room On Fire": 4.1,
    "Rubber Soul (Remastered 2009)": 4.5,
    "Rules": 4.3,
    "Rust Never Sleeps": 4.3,
    "Salad Days": 3.7,
    "Second Edition": 3.6,
    "Selected Ambient Works 85-92": 4.2,
    "Selected Ambient Works Volume II": 4.7,
    "Sgt. Pepper's Lonely Hearts Club Band (Remastered)": 4.8,
    "Shipsography": 3.9,
    "Shmap'n Shmazz (2025 Remaster)": 5,
    "Slanted & Enchanted": 3.9,
    "So Alone": 2.8,
    "Some Kind of Cadwallader": 3.8,
    "Spiderland (remastered)": 5,
    "Spirit of Eden": 4.9,
    "Starfucker": 4.7,
    "Starry Cat": 4.7,
    "Strange Geometry": 3.7,
    "Strangeways, Here We Come": 4.6,
    "Stratosphere": 4.9,
    "Strawberry Jam": 4,
    "Suburban Light (Remastered)": 4.7,
    "Suicide (2019 - Remaster)": 3.5,
    "Summer Brings the Sunshine": 3.7,
    "Sung Tongs": 3.7,
    "Super Ape": 3.5,
    "Surfer Rosa (Remastered)": 4.7,
    "Tago Mago (2011 Remastered)": 4.8,
    "Take The Kids Off Broadway": 3.4,
    "Teens of Denial": 4,
    "Tell Me About the Long Dark Path Home": 3.7,
    "The Beatles (Remastered)": 4.5,
    "The Beatles 1967 - 1970 (Remastered)": 4.8,
    "The Dark Side of the Moon": 4.1,
    "The Doors": 4.8,
    "The For Carnation": 3.5,
    "The Freewheelin' Bob Dylan": 4,
    "The Glow, Pt. 2": 4.9,
    "The Kinks Are The Village Green Preservation Society (2018 Stereo Remaster)": 3.7,
    "The Life Of Pablo": 3.9,
    "The Lonesome Crowded West": 4,
    "The Modern Lovers (Expanded Version)": 4,
    "The Mollusk": 4.2,
    "The New Abnormal": 3.9,
    "The Queen Is Dead": 4.1,
    "The Rise and Fall of Ziggy Stardust and the Spiders from Mars (2012 Remaster)": 5,
    "The Smiths": 4,
    "The Velvet Underground": 4,
    "The Velvet Underground & Nico 45th Anniversary": 5,
    "This Is a Long Drive for Someone with Nothing to Think About": 3.7,
    "This Is Happening": 4.1,
    "Three Imaginary Boys": 3.7,
    "Time Fades Away": 4.4,
    "To Pimp A Butterfly": 4,
    "Tonight's the Night": 3.6,
    "Too Bad Jim": 3.7,
    "Tourist History": 4.1,
    "Tow Truck Jesus": 4.3,
    "Transformer": 3.9,
    "Trash Island": 3.7,
    "Trick": 4.9,
    "Turn On The Bright Lights": 4.9,
    "Tweez": 3.5,
    "Twin Fantasy (Mirror To Mirror)": 4.9,
    "Unknown Memory": 3.6,
    "Wave": 3.3,
    "We Are the 21st Century Ambassadors of Peace & Magic": 3.4,
    "We're Only In It For The Money": 3.4,
    "Wede Harer Guzo": 4.8,
    "Weezer": 4.5,
    "What Burns Never Returns": 3.7,
    "White Light / White Heat (Deluxe Edition)": 4.6,
    "Wish You Were Here": 4.6,
    "Wlfgrl": 3.8,
    "Wowee Zowee": 3.8,
    "Yank Crime": 3.9,
    "Year Of The Snitch": 2.5,
    "Yeezus": 3.5,
    "Zachshots": 4.7,
    "Zuma": 4.5,
}
export default ratings;